repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix]

  - repo: local
    hooks:
      - id: unit-tests
        name: unit tests
        entry: python -m unittest discover -s tests -t .
        language: system
        pass_filenames: false
        stages: [pre-push]
